-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_USER u
JOIN USED_GOODS_BOARD b on u.USER_ID = b.WRITER_ID
WHERE b.STATUS = 'DONE'
GROUP BY u.USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;