SELECT
    YEAR(e1.DIFFERENTIATION_DATE) as YEAR,
    (
        SELECT MAX(SIZE_OF_COLONY)
        FROM ECOLI_DATA e2
        WHERE YEAR(e2.DIFFERENTIATION_DATE) = YEAR(e1.DIFFERENTIATION_DATE)
    ) - SIZE_OF_COLONY AS YEAR_DEV,
    e1.ID
FROM ECOLI_DATA e1
ORDER BY YEAR, YEAR_DEV;